// Brand list confirmed with the catalog owner. Brand splits families; it is never an option.
export const BRANDS = [
  { name: "Warma", match: ["warma"] },
  { name: "Rinnai", match: ["rinnai", "rinnaai", "rinna"] },
  { name: "TIS", match: ["tis", "tis."] },
  { name: "Atmos", match: ["atmos"] },
  { name: "Komeco", match: ["komeco", "kobc"] },
  { name: "Kawmet", match: ["kawmet"] },
  { name: "Texius", match: ["texius", "texus"] },
  { name: "Riello", match: ["riello"] },
  { name: "Kronus", match: ["kronus"] },
  { name: "Beretta", match: ["beretta"] },
  { name: "Kiturami", match: ["kiturami"] },
  { name: "LUX", match: ["lux"] },
  { name: "WEG", match: ["weg"] },
  { name: "Solis", match: ["solis"] },
  { name: "Kaori", match: ["kaori"] },
  { name: "Fogo Montanha", match: ["fogo montanha"] },
  { name: "Amanco", match: ["amanco"] },
  { name: "Heliodin", match: ["heliodin"] },
  { name: "Ferroli", match: ["ferroli"] },
  { name: "Neva", match: ["neva"] },
  { name: "Tholz", match: ["tholz"] },
  { name: "La Nordica Extraflame", match: ["la nordica extraflame", "la nordica"] },
  { name: "Nottitaliane", match: ["nottitaliane"] },
  { name: "Leapton", match: ["leapton"] },
  { name: "Canadian", match: ["canadian"] },
  { name: "Syllent", match: ["syllent"] },
  { name: "Lamborghini", match: ["lamborghinieco", "lamborghini"] },
  { name: "Termomax", match: ["thermomax", "termomax"] },
  { name: "Ecal", match: ["ecal", "ecl"] },
];
